export enum tag {
    HIGH_PROTEIN = "HIGH_PROTEIN",
    LOW_CALORIES = "LOW_CALORIES",
    HIGH_PROTEIN_LOW_CALORIES = "HIGH_PROTEIN_LOW_CALORIES",
    LOW_FAT = "LOW_FAT",
    VEGAN = "VEGAN",
    VEGETARIAN = "VEGETARIAN",
    GLUTEN_FREE = "GLUTEN_FREE",
    DAIRY_FREE = "DAIRY_FREE",
    LOW_CARB = "LOW_CARB",
    KETO = "KETO"
}